/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_Slave.h"
#include "I2C_Slave_I2C.h"
#include "I2C_Slave_PINS.h"
#include "I2C_Slave_I2C_PVT.h"
#include "I2C_Slave_PVT.h"
#include "I2C_Slave_BOOT.h"
#include "LED.h"
#include "LED_aliases.h"
#include "I2C_Master.h"
#include "I2C_Master_I2C.h"
#include "I2C_Master_PINS.h"
#include "I2C_Master_I2C_PVT.h"
#include "I2C_Master_PVT.h"
#include "I2C_Master_BOOT.h"
#include "UART.h"
#include "I2C_Slave_SCBCLK.h"
#include "I2C_Slave_sda.h"
#include "I2C_Slave_sda_aliases.h"
#include "I2C_Slave_scl.h"
#include "I2C_Slave_scl_aliases.h"
#include "I2C_Slave_SCB_IRQ.h"
#include "I2C_Master_SCBCLK.h"
#include "I2C_Master_sda.h"
#include "I2C_Master_sda_aliases.h"
#include "I2C_Master_scl.h"
#include "I2C_Master_scl_aliases.h"
#include "I2C_Master_SCB_IRQ.h"
#include "UART_IntClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

